src/apps/image_storage/urls.py
from django.conf.urls import url
from .views import ListImage, UpdateView, AddImage, DeleteImage, search

urlpatterns = [
    url(r'^$', ListImage.as_view(), name='index'),
    url(r'image-(?P<pk>\d+)/edit/', UpdateView.as_view(), name='edit'),
    url(r'add/', AddImage.as_view(), name='add'),
    url(r'image-(?P<pk>\d+)/delete/', DeleteImage.as_view(), name='delete'),

    url(r'search/', search, name='search'),
]

src/core/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.image_storage.urls', namespace='storage')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/image_storage/models.py
from django.db import models
from datetime import datetime
from ckeditor.fields import RichTextField


class Image(models.Model):
    """
    Image model
    """
    title = models.CharField(verbose_name='Название', max_length=75, default='')
    image = models.ImageField(verbose_name='Изображение', default='')
    description = RichTextField(verbose_name='Описание', default='')
    date_taken = models.DateField(verbose_name='Дата сьемки', default=datetime.now(), db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('date_taken',)
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

src/apps/image_storage/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from .models import Image
from .widgets import Datepicker


class ImageForm(object):
    bootstrap_form_class = 'form-control'
    description = forms.CharField(widget=CKEditorWidget(), label='Описание')

    def __init__(self, *args, **kwargs):
        super(ImageForm, self).__init__(*args, **kwargs)
        self.fields['date_taken'].label = 'Укажите дату сьемки'
        for name, field in self.fields.items():
            if 'class' in field.widget.attrs:
                field.widget.attrs['class'] += ' {}'.format(self.bootstrap_form_class)
            else:
                field.widget.attrs.update({'class': self.bootstrap_form_class})


class ImageEditForm(ImageForm, forms.ModelForm):
    date_taken = forms.DateField(widget=Datepicker(), label='Укажите дату сьемки')

    class Meta:
        model = Image
        fields = (
            'title',
            'description',
            'date_taken',
        )


class ImageUploadForm(ImageForm, forms.ModelForm):
    date_taken = forms.DateField(widget=Datepicker(), label='Укажите дату сьемки')

    class Meta:
        model = Image
        fields = (
            'title',
            'image',
            'description',
            'date_taken',
        )

src/apps/image_storage/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .filter import ImageFilter
from .models import Image
from .forms import ImageUploadForm, ImageEditForm


def search(request):
    template_name = 'image_storage/search.html'

    _filter = ImageFilter(request.GET, queryset=Image.objects.all())
    return render(request, template_name, {
        'filter': _filter
    })


class ListImage(generic.ListView):
    model = Image
    template_name = 'image_storage/index.html'
    context_object_name = 'images'
    paginate_by = 9


class UpdateView(generic.UpdateView):
    model = Image
    form_class = ImageEditForm
    template_name = 'image_storage/_update_image.html'
    context_object_name = 'image'
    success_message = 'Изображение изменено'

    def form_valid(self, form):
        super(UpdateView, self).form_valid(form)
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('storage:edit', kwargs={'pk': self.get_object().id})


class AddImage(generic.FormView):
    form_class = ImageUploadForm
    template_name = 'image_storage/_add_image.html'
    success_message = 'Изображение добавлено'

    def form_valid(self, form):
        form.save()
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('storage:add')


class DeleteImage(generic.DeleteView):
    model = Image
    success_url = reverse_lazy('storage:index')

    def dispatch(self, *args, **kwargs):
        response = super(DeleteImage, self).dispatch(*args, **kwargs)
        if self.request.is_ajax():
            response_data = {"result": "ok"}
            return JsonResponse(response_data)
        else:
            return response

src/apps/image_storage/templates/image_storage/_add_image.html
{% extends 'image_storage/_layout.html' %}

{% block title %}Добавить изображение{% endblock %}
{% block page_header %}Добавить изображение{% endblock %}
{% block page_control %}
  <a href="{% url 'storage:index' %}" class="back">Вернуться</a>
{% endblock %}

{% block content %}

  <div class="container">

    <div class="form-upload">
      {% if messages %}
        <div class="alert alert-success" role="alert">
          <ul class="messages">
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
          </ul>
        </div>

      {% endif %}
      <form action="{% url 'storage:add' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
        {{ form.media }}

        {% for field in form %}
          <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {% if field.errors %}
              <div class="alert alert-danger" role="alert">
                {{ form.errors }}
              </div>
            {% endif %}
          </div>
        {% endfor %}
        {#      <div class="input-group mb-3">#}
        {#        {{ form.date_taken.label_tag }}#}
        {#        <div class="">#}
        {#        <div class="input-group-prepend">#}
        {#          <span class="input-group-text date_picker"></span>#}
        {#        </div>#}
        {#        {{ form.date_taken }}#}
        {#      </div>#}

        <div class="input-group">
          <button type=”submit” class="btn btn-success">Отправить</button>
        </div>
      </form>
    </div>


  </div>


{% endblock %}

src/apps/image_storage/templates/image_storage/_delete_image.html
<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm"/>
</form>

src/apps/image_storage/templates/image_storage/_layout.html
{% load render_bundle from webpack_loader %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock %}</title>

  {% render_bundle 'main' 'css' %}
  {% block extra_head %}{% endblock %}
  {% block custom_page_js %}{% endblock %}

</head>
<body>

<header class="site-header">
  <div class="container">
    <div class="page__control">
      {% block page_control %}{% endblock %}
    </div>
    <div class="page__header">
      <h1 class="thin">{% block page_header %}{% endblock %}</h1>
    </div>
  </div>
</header>
<main>
  {% block content %}{% endblock %}
</main>


{% block extra_js_before %}{% endblock %}
{% render_bundle 'main' 'js' %}
{% block extra_js_after %}{% endblock %}
</body>
</html>

src/apps/image_storage/templates/image_storage/_update_image.html
{% extends 'image_storage/_layout.html' %}

{% load thumbnail %}

{% block title %}Редактирование изображения{% endblock %}
{% block page_header %}Редактирование изображения{% endblock %}
{% block page_control %}
  <a href="{% url 'storage:index' %}" class="back">Вернуться</a>
{% endblock %}

{% block content %}

  <div class="container">

    <div class="card-detail">
      <div class="card-detail-wrapper">
        <div class="card-detail-info">

          {% if messages %}
            <div class="alert alert-success" role="alert">
              <ul class="messages">
                {% for message in messages %}
                  <li>{{ message }}</li>
                {% endfor %}
              </ul>
            </div>
          {% endif %}

          <form action="{% url 'storage:edit' image.id %}" method="post">
            {% csrf_token %}
            {% if form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% endif %}
            {{ form.media }}

            {% for field in form %}
              <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% if field.errors %}
                  <div class="alert alert-danger" role="alert">
                    {{ form.errors }}
                  </div>
                {% endif %}
              </div>
            {% endfor %}

            <div class="input-group">
              <button type=”submit” class="btn btn-success">Отправить</button>
            </div>
          </form>
        </div>
        <div class="card-detail-photo">
          {% thumbnail image.image "400x440" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
        </div>
      </div>
    </div>
  </div>

{% endblock %}

src/apps/image_storage/templates/image_storage/index.html
{% extends 'image_storage/_layout.html' %}

{% load thumbnail %}

{% block title %}Хранилище изображений{% endblock %}
{% block page_header %}Хранилище картинок{% endblock %}
{% block page_control %}
  <a href="{% url 'storage:add' %}" class="btn btn-success">Добавить</a>
  <a href="{% url 'storage:search' %}" class="btn btn-default">Искать <i class="material-icons">arrow_forward</i></a>
{% endblock %}

{% block content %}

  <div class="container">

    <div class="gallery">
      <div class="gallery-list">
        {% for item in images %}
          <div class="card">
            <div class="card__cover">
              <a href="{% url 'storage:edit' item.id %}">
                {% thumbnail item.image "354x224" crop="center" as im %}
                  <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
              </a>
            </div>
            <div class="card__panel">
              <div class="card__panel-inner">
                <div class="card__info">
                  <a href="{% url 'storage:edit' item.id %}">
                    <span class="card__info-title">{{ item.title }}</span>
                    <span class="card__info-description">{{ item.description | safe }}</span>
                    <span class="card__info-date">{{ item.date_taken }}</span>
                  </a>
                </div>
                <div class="card__options">
                  <a href="{% url 'storage:delete' item.id %}" tooltip="Удалить" flow="right" class="delete">
                    <i class="material-icons">delete</i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <nav class="">
      {% if is_paginated %}
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="prev"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
          {% else %}
            <li class="disabled"><span class="page-link">&laquo;</span></li>
          {% endif %}
          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="next"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
          {% else %}
            <li class="disabled"><span class="page-link">&raquo;</span></li>
          {% endif %}
        </ul>
      {% endif %}
    </nav>
  </div>


{% endblock %}

src/apps/image_storage/templates/image_storage/search.html
{% extends 'image_storage/_layout.html' %}

{% load thumbnail %}
{% load static %}

{% block title %}Искать{% endblock %}
{% block page_header %}Искать{% endblock %}
{% block page_control %}
  <a href="{% url 'storage:index' %}" class="back">Вернуться</a>
{% endblock %}

{% block content %}

  <div class="container">


    <div class="gallery">
      <div class="search-form">
        <form action="" method="get">
          {% for f in filter.form %}
            <div class="form-group">
              {{ f.label_tag }}
              {{ f }}
            </div>
          {% endfor %}
          <button class="btn btn-success" type="submit">Искать</button>
        </form>
      </div>
      <div class="gallery-list">
        {% for item in filter.qs %}
          <div class="card">
            <div class="card__cover">
              <a href="{% url 'storage:edit' item.id %}">
                {% thumbnail item.image "354x224" crop="center" as im %}
                  <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
              </a>
            </div>
            <div class="card__panel">
              <div class="card__panel-inner">
                <div class="card__info">
                  <a href="{% url 'storage:edit' item.id %}">
                    <span class="card__info-title">{{ item.title }}</span>
                    <span class="card__info-description">{{ item.description | safe }}</span>
                    <span class="card__info-date">{{ item.date_taken }}</span>
                  </a>
                </div>
                <div class="card__options">
                  <a href="{% url 'storage:delete' item.id %}" tooltip="Удалить" flow="right" class="delete">
                    <i class="material-icons">delete</i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <nav class="">
      {% if is_paginated %}
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="prev"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
          {% else %}
            <li class="disabled"><span class="page-link">&laquo;</span></li>
          {% endif %}
          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="next"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
          {% else %}
            <li class="disabled"><span class="page-link">&raquo;</span></li>
          {% endif %}
        </ul>
      {% endif %}
    </nav>
  </div>


{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'datepicker/datepicker.min.css' %}">
{% endblock %}

{% block extra_js_after %}
  <script type="application/javascript" src="{% static 'datepicker/jquery.min.js' %}"></script>
  <script type="application/javascript" src="{% static 'datepicker/datepicker.min.js' %}"></script>
  <script type="application/javascript" src="{% static 'datepicker/field.js' %}"></script>
{% endblock %}